// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzgrtjwcmyjcinjyiosk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6Z3J0andjbXlqY2luanlpb3NrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NDQ0ODcsImV4cCI6MjA3MTQyMDQ4N30.0OVpJADoZ-dPRLwJhPSQRACmB0ToGE3z-yT3lK0XCx0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
    heartbeatIntervalMs: 30000,
    reconnectIntervalMs: 5000,
  },
  db: {
    schema: 'public',
  },
});